spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${JWT_ACCESS_EXP}
    refreshTokenExpiration: ${JWT_REFRESH_EXP}

springdoc:
  swagger-ui:
    enabled: false  # 운영에서는 Swagger 비활성화
  api-docs:
    enabled: false

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.springframework: warn
